site_name: Bayesian Geometric Forest
site_description: Bayesian Spanning Forest and Forest Process for Robust Graphical Model-Based Spectral Clustering
site_author: Bobby Zhang
repo_url: https://github.com/numberingeometry/bayesian-geometric-forest

theme:
  name: readthedocs

plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true

nav:
  - Overview: index.md
  - Theory & Mathematics: theory.md
